src/Web/WebMVC/Models/ErrorViewModel.cs
using System;

namespace WebMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Web/WebMVC/Models/JwtTokenDTO.cs
using System;
using Newtonsoft.Json;

namespace WebMVC.Models
{
    public class JwtTokenDTO
    {
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        [JsonProperty(PropertyName = "expiration")]
        public DateTimeOffset Expiration { get; set; }
    }
}

src/Web/WebMVC/Models/PaginatedItemsViewModel.cs
using System.Collections.Generic;

namespace WebMVC.Models
{
    public class PaginatedItemsViewModel<TEntity> where TEntity : class
    {
        public int PageIndex { get; }
        public int PageSize { get; }
        public long Count { get; }
        public IEnumerable<TEntity> Data { get; }

        public PaginatedItemsViewModel(int pageIndex, int pageSize, long count, IEnumerable<TEntity> data)
        {
            this.PageIndex = pageIndex;
            this.PageSize = pageSize;
            this.Count = count;
            this.Data = data;
        }
    }
}

src/Web/WebMVC/ViewModels/Account/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebMVC.ViewModels.Account
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }

        public string ReturnUrl { get; set; }
    }
}

src/Web/WebMVC/ViewModels/Reminder/ReminderViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebMVC.ViewModels.Reminder
{
    public class ReminderViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset Date { get; set; }
        public string Notes { get; set; }

        [Display(Name = "Completion Date")]
        [DataType(DataType.DateTime)]
        public DateTimeOffset? CompletionDate { get; set; }

        public DateTimeOffset CreationDate { get; set; }
        public DateTimeOffset? LastUpdateDate { get; set; }
    }
}

src/Web/WebMVC/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Services;
using WebMVC.ViewModels.Account;

namespace WebMVC.Controllers
{
    public class AccountController : Controller
    {
        #region | Fields

        private readonly IIdentityService _identityService;

        #endregion

        #region | Constructors

        public AccountController(
            IIdentityService identityService)
        {
            _identityService = identityService;
        }

        #endregion

        #region | Public Methods

        #region | GET: /Login

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            var vm = new LoginViewModel();
            ViewData["ReturnUrl"] = returnUrl;

            return View(vm);
        }

        #endregion

        #region | POST: /Login

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tokenResponse = await _identityService.Token(model.Email, model.Password);

                if (tokenResponse == null)
                {
                    ModelState.AddModelError("", "Invalid username or password.");
                }
                else
                {
                    var jwtToken = new JwtSecurityTokenHandler().ReadJwtToken(tokenResponse.Token);
                    var principal = new ClaimsPrincipal();
                    principal.AddIdentity(new ClaimsIdentity(
                        jwtToken.Claims.Union(
                        new List<Claim>() { new Claim("access_token", tokenResponse.Token) })
                    ));

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal,
                        new AuthenticationProperties(new Dictionary<string, string>(){{"token_expires", tokenResponse.Expiration.ToString("O")}}));
                }
            }

            // something went wrong, show form with error
            var vm = new LoginViewModel() { Email = model.Email };
            ViewData["ReturnUrl"] = model.ReturnUrl;
            return View(vm);
        }

        #endregion

        #region | POST: /Signout

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Signout()
        {
            await HttpContext.SignOutAsync("Cookies");
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        #endregion

        #endregion
    }
}

src/Web/WebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Web/WebMVC/Controllers/RemindersController.cs
using System.Threading.Tasks;
using Framework.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebMVC.Services;

namespace WebMVC.Controllers
{
    [Authorize]
    public class RemindersController : Controller
    {
        #region | Fields

        private readonly IReminderService _reminderService;
        private readonly ILogger<RemindersController> _logger;

        #endregion

        #region | Constructors

        public RemindersController(
            IReminderService reminderService,
            ILogger<RemindersController> logger)
        {
            _reminderService = reminderService;
            _logger = logger;
        }

        #endregion

        #region | Public Methods

        #region | Items - GET: /Index[?pageSize={pageSize}&pageIndex={pageIndex}]

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] int pageSize = 10, [FromQuery] int pageIndex = 0)
        {
            _logger.LogInformation("Index");

            var model = await _reminderService.Items(pageSize: pageSize, pageIndex: pageIndex);
            return View(model);
        }

        #endregion

        #endregion
    }
}

src/Web/WebMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Web/WebMVC/Views/Reminders/Index.cshtml
@model PaginatedItemsViewModel<WebMVC.ViewModels.Reminder.ReminderViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<a asp-action="Create">Create New</a>

<table class="table">
  <thead>
    <tr>
      <td>@Html.DisplayNameFor(model => model.Data.First().Title)</td>
      <td>@Html.DisplayNameFor(model => model.Data.First().Notes)</td>
      <td>@Html.DisplayNameFor(model => model.Data.First().Date)</td>
      <td>@Html.DisplayNameFor(model => model.Data.First().CompletionDate)</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model.Data)
    {
        <tr>
          <td>@Html.DisplayFor(modelItem => item.Title)</td>
          <td>@Html.DisplayFor(modelItem => item.Notes)</td>
          <td>@Html.DisplayFor(modelItem => item.Date)</td>
          <td>@Html.DisplayFor(modelItem => item.CompletionDate)</td>
          <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
          </td>
        </tr>
    }
  </tbody>
</table>

src/Web/WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - WebMVC</title>

  <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
  </environment>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a asp-area="" asp-controller="Reminders" asp-action="Index" class="navbar-brand">WebMVC</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a asp-area="" asp-controller="Reminders" asp-action="Index">Reminders</a></li>
        </ul>
        @await Html.PartialAsync("_LoginPartial")
      </div>
    </div>
  </nav>
  <div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
      <p>&copy; 2017 - Reminders on containers</p>
    </footer>
  </div>

  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
  </environment>

  @RenderSection("Scripts", required: false)
</body>
</html>